app:
  info:
    ### 系统访问地址
    host: http://192.168.50.194:21013
    # 服务器集群中当前运行服务器标识
    serverCurrentHost: local
  file:
    # 基础文件夹路径
    basePath: D:/gfk/app
# 端口号
server:
  port: 21013
  ## 关闭优雅停机
  shutdown: IMMEDIATE
## 缓冲器即最大等待时间
spring:
  lifecycle:
    timeout-per-shutdown-phase: 0s

# 本地开发环境配置
properties:
  spring:
    datasource:
      # 数据库配置
      url: jdbc:mysql://192.168.56.101:3306/gfk?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&rewriteBatchedStatements=true
      username: root
      password: root
      # Druid配置
      druid:
        stat-view-servlet:
          login-username: druid
          login-password: druid
    # Redis配置
    redis:
      host: 192.168.56.101
      port: 6379
      database: 8
      password: